// Code generated by swagger.main.go. DO NOT EDIT.
package swagger

var GATEWAY_JSON = `{
  "swagger": "2.0",
  "info": {
    "title": "gateway.proto",
    "version": "version not set"
  },
  "tags": [
    {
      "name": "Gateway"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/medicalpoint/admin": {
      "delete": {
        "summary": "Delete Admin from chain, not delete in database",
        "operationId": "Gateway_DeleteAdmin",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainDeleteAdminResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainDeleteAdminRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      },
      "post": {
        "summary": "Add admin",
        "operationId": "Gateway_PostAdmin",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostAdminResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostAdminRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/admin-transfer": {
      "post": {
        "summary": "Admin transfer point from system to user",
        "operationId": "Gateway_PostAdminTransfer",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostAdminTransferResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostAdminTransferRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/admins": {
      "get": {
        "summary": "Get admin",
        "operationId": "Gateway_GetAdmin",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainGetAdminResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/balance": {
      "get": {
        "summary": "Get Balance",
        "operationId": "Gateway_GetBalance",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainGetBalanceResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "userId",
            "description": "userId of user in main server that want to check balance.",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/burn": {
      "post": {
        "summary": "Burn point",
        "operationId": "Gateway_PostBurn",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostBurnResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostBurnRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/mint": {
      "post": {
        "summary": "Mint point",
        "operationId": "Gateway_PostMint",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostMintResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostMintRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/super-admin": {
      "post": {
        "summary": "Init Super admin",
        "operationId": "Gateway_PostSuperAdmin",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostSuperAdminResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/system-balance": {
      "get": {
        "summary": "Get system balances",
        "operationId": "Gateway_GetSystemBalance",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainGetSystemBalanceResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/transfer": {
      "post": {
        "summary": "Transfer point from user to user",
        "operationId": "Gateway_PostTransfer",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostTransferResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostTransferRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    },
    "/medicalpoint/users": {
      "post": {
        "summary": "Create User",
        "operationId": "Gateway_PostUser",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/medical_chainPostUserResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/medical_chainPostUserRequest"
            }
          }
        ],
        "tags": [
          "Gateway"
        ]
      }
    }
  },
  "definitions": {
    "medical_chainDeleteAdminRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId of superadmin in main server"
        },
        "adminId": {
          "type": "string",
          "title": "adminId of admin to delete"
        }
      }
    },
    "medical_chainDeleteAdminResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "adminId": {
          "type": "string"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction delete-admin"
        }
      }
    },
    "medical_chainGetAdminResponse": {
      "type": "object"
    },
    "medical_chainGetBalanceResponse": {
      "type": "object",
      "properties": {
        "balances": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/medical_chainGetBalanceResponsePoint"
          },
          "title": "list of balances"
        }
      }
    },
    "medical_chainGetBalanceResponsePoint": {
      "type": "object",
      "properties": {
        "denom": {
          "type": "string",
          "title": "denom name of token"
        },
        "amount": {
          "type": "string",
          "title": "amount of token"
        }
      }
    },
    "medical_chainGetSystemBalanceResponse": {
      "type": "object",
      "properties": {
        "balances": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/medical_chainGetSystemBalanceResponsePoint"
          },
          "title": "list of balances"
        }
      }
    },
    "medical_chainGetSystemBalanceResponsePoint": {
      "type": "object",
      "properties": {
        "denom": {
          "type": "string",
          "title": "denom name of token"
        },
        "amount": {
          "type": "string",
          "title": "amount of token"
        }
      }
    },
    "medical_chainPostAdminRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId of superadmin in main server"
        },
        "adminId": {
          "type": "string",
          "title": "adminId of admin to add"
        }
      }
    },
    "medical_chainPostAdminResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "adminId": {
          "type": "string"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction create-admin"
        }
      }
    },
    "medical_chainPostAdminTransferRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId of sender admin in main server"
        },
        "to": {
          "type": "string",
          "title": "userId of reciever user in main server"
        },
        "amount": {
          "type": "string",
          "title": "amount of token to transfer"
        },
        "denom": {
          "type": "string",
          "title": "denom name of token to transfer (eg: point)"
        }
      }
    },
    "medical_chainPostAdminTransferResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "amount": {
          "type": "string",
          "title": "amount of token has been transfered"
        },
        "denom": {
          "type": "string"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction admin-transfer"
        }
      }
    },
    "medical_chainPostBurnRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId of superadmin in main server"
        },
        "amount": {
          "type": "string",
          "title": "amount of token to burn"
        }
      }
    },
    "medical_chainPostBurnResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "amount": {
          "type": "string",
          "title": "amount of token has been burned"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction burn"
        }
      }
    },
    "medical_chainPostMintRequest": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "string",
          "title": "amount of token to mint"
        },
        "userId": {
          "type": "string",
          "title": "userId of superadmin in main server"
        }
      }
    },
    "medical_chainPostMintResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "amount": {
          "type": "string",
          "title": "amount of token has been minted"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction mint"
        }
      }
    },
    "medical_chainPostSuperAdminResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "medical_chainPostTransferRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId of sender user in main server"
        },
        "to": {
          "type": "string",
          "title": "userId of reciever user in main server"
        },
        "amount": {
          "type": "string",
          "title": "amount of token to transfer"
        },
        "denom": {
          "type": "string",
          "title": "denom name of token to transfer (eg: point)"
        }
      }
    },
    "medical_chainPostTransferResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "amount": {
          "type": "string",
          "title": "amount of token has been transfered"
        },
        "denom": {
          "type": "string"
        },
        "txh": {
          "type": "string",
          "title": "txh of transaction transfer"
        }
      }
    },
    "medical_chainPostUserRequest": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId in main server"
        }
      }
    },
    "medical_chainPostUserResponse": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string",
          "title": "userId in main server"
        }
      }
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    }
  }
}
`
