version: "3.7"
services:
  chain:
    image: aqaurius6666/medipoint-chain:latest
    # build: 
    #   dockerfile: chain.Dockerfile
    #   context: .
    ports:
      - "9191:9090"
      - "26657:26657"
    user: root
    command:
      - /bin/sh
      - -c
      - |
        ./init-chain.sh
    volumes:
      - .chain:/root/.medipoint
    environment:
      - MONIKER=medicalpoint
      - CHAIN_ID=test-chain
      - VALIDATOR_MNEMONIC=hotel sword swarm scissors desk chase illegal idea noise humble track orient spare nurse dad insect agent prison learn polar talk soccer sadness above
      - VALIDATOR_ACCOUNT=validator1
      - AMOUNT=1000000000000000000stake
      - SUPER_ADMIN_ADDRESS=medipoint1yvhdw3ups243zmxx9hvq3t5skm8ggyme86wv5n
  gateway-cdb:
    image: cockroachdb/cockroach:v21.1.6
    ports:
      - "26259:26257"
    command: start-single-node --insecure
    volumes:
      - "./.db:/cockroach/cockroach-data"

  gateway:
    image: aqaurius6666/medicalpoint-gateway:latest
    ports:
      - "10998:80"
    depends_on:
      - gateway-cdb
      - chain
    command:
      - /bin/sh
      - -c
      - |
        server serve
    environment:
      - DISABLE_TRACING=true
      - DISABLE_PROFILER=true
      - VERSION=0.0.1
      - HTTP_PORT=80
      - GRPC_PORT=50051
      - PPROF_PORT=6000
      - DISABLE_STATS=true
      - DB_URI=postgresql://root:root@gateway-cdb:26257/defaultdb?sslmode=disable
      - LOG_LEVEL=debug
      - LOG_FORMAT=plain
      - COSMOS_ENDPOINT=chain:9090
      - MNEMONIC=hotel sword swarm scissors desk chase illegal idea noise humble track orient spare nurse dad insect agent prison learn polar talk soccer sadness above
      - CHAIN_ID=test-chain
      - GCFLAGS
      - ENCRYPT_KEY=31237147183974198324719247184

volumes:
  .chain: