// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package api

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/medicalpoint/gateway/src/db"
	"github.com/sirupsen/logrus"
)

// Injectors from index.wire.go:

func InitApiService(ctx context.Context, opts ApiServiceOptions) (*GateWayServer, error) {
	engine := gin.New()
	gateWayServiceRepo := opts.GateWayCDBRepo
	logger := opts.Logger
	blockchainService := &BlockchainService{
		db:     gateWayServiceRepo,
		logger: logger,
	}
	blockchainApi := &BlockchainApi{
		blockchainService: blockchainService,
		logger:            logger,
	}
	gateWayServer := &GateWayServer{
		G:          engine,
		blockchain: blockchainApi,
	}
	return gateWayServer, nil
}

// index.wire.go:

type ApiServiceOptions struct {
	Logger         *logrus.Logger
	GateWayCDBRepo db.GateWayServiceRepo
}
