// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cockroach

import (
	"context"
	"github.com/medicalpoint/gateway/src/db/cockroach/user"
	"github.com/sirupsen/logrus"
	"github.com/sonntuet1997/medical-chain-utils/cockroach"
)

// Injectors from gateway.repo.wire.cdb.go:

func InitGatewayCDBRepo(ctx context.Context, opts GatewayCDBRepoOptions) (*GatewayCDBRepo, error) {
	logger := opts.Logger
	string2 := opts.Dsn
	db, err := cockroach.NewCDBConnection(string2)
	if err != nil {
		return nil, err
	}
	userCDBRepo, err := user.InitUserCDBRepo(ctx, logger, db)
	if err != nil {
		return nil, err
	}
	gatewayCDBRepo := &GatewayCDBRepo{
		UserCDBRepo: userCDBRepo,
	}
	return gatewayCDBRepo, nil
}

// gateway.repo.wire.cdb.go:

type GatewayCDBRepoOptions struct {
	Dsn    string
	Logger *logrus.Logger
}
